require "flame/version"
require "flame/generators/cors_generator"
require "flame/generators/testing_generator"
require "flame/generators/devise_generator"
require "flame/generators/vite_generator"
require "flame/generators/haml_generator"
require "flame/generators/app"
require "flame/app_builder"
